version: "3"

# We define two services, meaning that we will have two running containers
services:
# The first one is our flask container
  flask:
  # Viold the DOckerfile inside the flask folder
    build: ./flask 
    # and give this conationer tyhe name flask
    container_name: flask
    # If something bad happens, restart the container
    restart: always
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"